CREATE TABLE Company_Info(
loc TEXT NOT NULL,
edu TEXT NOT NULL,
co_size TEXT NOT NULL,
co_name TEXT NOT NULL,
notice_title TEXT NOT NULL,
deadline TEXT NOT NULL,
duty TEXT NOT NULL,
working_date TEXT NOT NULL,
intake TEXT NOT NULL,
notice_addr TEXT NOT NULL,
co_site TEXT NOT NULL,
co_addr TEXT NOT NULL,
CEO_name TEXT NOT NULL,
est_date TEXT NOT NULL,
employee_num TEXT NOT NULL,
revenue TEXT NOT NULL,
biz_cat TEXT NOT NULL,
biz_content TEXT NOT NULL,
company_num INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT);
